### ISSUE TITLE
guest user generation concept

### ISSUE THREAD

**Issue by alegrm** [GeoKnow/GeoKnowGeneratorUI#48]
In order to facilitate the testing of the workbench, instead of requesting the user to register, we want to be able to generate a one-access guest user that can have a guided tour. 
So the guest users will access to the workbench (may be use a captcha to avoid the access to non-humans). and this action will generate a guest user and setup some initial datasets so the user can do his tour.

**Comment by jonasch** [comment]
This will be solved by enhancing the backend API for Logins, where a user 'demo{number}' gets registered and has the demo user role. when he logs out, all his graphs etc. gets deleted.
