### ISSUE TITLE
Cannot open multiple tool popups

### ISSUE THREAD

**Issue by jonjaylegrange** [GeoKnow/GeoKnowGeneratorUI#9]
It is not possible to start two LIMES or TripleGeo etc jobs simultaneously. A new job can only be started once the popup for the tool in question has been closed.

Attempting to start a different tool (e.g. LIMES) while another is running (e.g. GeoLift) opens the LIMES popup in the GeoLift popup.

**Comment by alegrm** [comment]
No more popups with the batch processing
